name: CI
on:
  push:
    # branches:
    #   - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: yarn | grep -v 'YN0013'
      - run: yarn run build

      - uses: actions/upload-artifact@v2
        with:
          name: dists
          path: packages/apps/build/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: packages/apps/build # Do not add prefix or suffix slash!
          CLEAN: true
